### ISSUE TITLE
Support for spaces in Project Path

### ISSUE THREAD

**Issue by Knapsack44** [bchatard/alfred-jetbrains#12]
Q | A
--- | ---
Workflow version | _1.0.6_
OSX Version | _10.14.4_
Alfred Version | _3.8.1_
JetBrains Product/Version | _PyCharm / 2019.1.1_
Installation type | _JB Toolbox_

### Description
When the project path contains a space, it won't be listed in the results.
For clarification see https://imgur.com/a/nOHBWn8. The first two projects contain spaces in their project paths.

### Step to reproduce
Create a project within a path with spaces.

PS: Thanks a lot for your awesome workflow :-).

**Comment by bchatard** [comment]
@Knapsack44 thanks for your support and issue reporting :)
I will look on this issue asap

**Comment by bchatard** [comment]
@Knapsack44 
I can't reproduce the issue

![image](https://user-images.githubusercontent.com/829364/55964240-abcfe100-5c74-11e9-8d01-2116042d8a97.png)

I just released a new version, with a bug fix, can you give a try to latest version?

**Comment by Knapsack44** [comment]
@bchatard Thanks for your lightning fast response.
Now the projects get listed but I still can't open them. See https://v.usetapes.com/Eq6oKkUhjG

**Comment by Knapsack44** [comment]
Here's the full debug log:
```
Starting debug for 'JetBrains - Open Project - v3'

[2019-04-11 16:51:48][input.scriptfilter] Queuing argument ''
[2019-04-11 16:51:49][input.scriptfilter] Script with argument '' finished
[2019-04-11 16:51:49][input.scriptfilter] {
	"items": [
		{
			"uid": "project with spaces",
			"title": "project with spaces",
			"match": "project with spaces",
			"subtitle": "/Users/markus/PycharmProjects/project with spaces",
			"arg": "/Users/markus/PycharmProjects/project with spaces",
			"autocomplete": "project with spaces",
			"text": {
				"copy": "/Users/markus/PycharmProjects/project with spaces",
				"largetype": "project with spaces"
			},
			"icon": {
				"path": "/Users/markus/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app",
				"type": "fileicon"
			},
			"variables": {
				"jb_project_name": "project with spaces",
				"jb_bin": "/usr/local/bin/pycharm"
			}
		},
		{
			"uid": "testproject",
			"title": "testproject",
			"match": "testproject",
			"subtitle": "/Users/markus/PycharmProjects/Pfad mit Leerzeichen/testproject",
			"arg": "/Users/markus/PycharmProjects/Pfad mit Leerzeichen/testproject",
			"autocomplete": "testproject",
			"text": {
				"copy": "/Users/markus/PycharmProjects/Pfad mit Leerzeichen/testproject",
				"largetype": "testproject"
			},
			"icon": {
				"path": "/Users/markus/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app",
				"type": "fileicon"
			},
			"variables": {
				"jb_project_name": "testproject",
				"jb_bin": "/usr/local/bin/pycharm"
			}
		},
		{
			"uid": "Themis Parser",
			"title": "Themis Parser",
			"match": "Themis Parser",
			"subtitle": "/Users/markus/Seafile/Meine Bibliothek/Dokumente/FH-Trier/2017WS/Projektstudium/Themis Stuff/Themis Parser",
			"arg": "/Users/markus/Seafile/Meine Bibliothek/Dokumente/FH-Trier/2017WS/Projektstudium/Themis Stuff/Themis Parser",
			"autocomplete": "Themis Parser",
			"text": {
				"copy": "/Users/markus/Seafile/Meine Bibliothek/Dokumente/FH-Trier/2017WS/Projektstudium/Themis Stuff/Themis Parser",
				"largetype": "Themis Parser"
			},
			"icon": {
				"path": "/Users/markus/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app",
				"type": "fileicon"
			},
			"variables": {
				"jb_project_name": "Themis Parser",
				"jb_bin": "/usr/local/bin/pycharm"
			}
		},
		{
			"uid": "PythonPlayground",
			"title": "PythonPlayground",
			"match": "PythonPlayground",
			"subtitle": "/Users/markus/PycharmProjects/PythonPlayground",
			"arg": "/Users/markus/PycharmProjects/PythonPlayground",
			"autocomplete": "PythonPlayground",
			"text": {
				"copy": "/Users/markus/PycharmProjects/PythonPlayground",
				"largetype": "PythonPlayground"
			},
			"icon": {
				"path": "/Users/markus/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app",
				"type": "fileicon"
			},
			"variables": {
				"jb_project_name": "PythonPlayground",
				"jb_bin": "/usr/local/bin/pycharm"
			}
		},
		{
			"uid": "untitled",
			"title": "untitled",
			"match": "untitled",
			"subtitle": "/Users/markus/PycharmProjects/untitled",
			"arg": "/Users/markus/PycharmProjects/untitled",
			"autocomplete": "untitled",
			"text": {
				"copy": "/Users/markus/PycharmProjects/untitled",
				"largetype": "untitled"
			},
			"icon": {
				"path": "/Users/markus/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/191.6605.12/PyCharm.app",
				"type": "fileicon"
			},
			"variables": {
				"jb_project_name": "untitled",
				"jb_bin": "/usr/local/bin/pycharm"
			}
		},
		{
			"title": "Retrieve Product: 35ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		},
		{
			"title": "Retrieve Projects: 9ms",
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Clock.icns"
			}
		}
	]
}
[2019-04-11 16:51:51][input.scriptfilter] Processing output of 'action.script' with arg '/Users/markus/PycharmProjects/project with spaces'
[2019-04-11 16:51:51][ERROR: action.script] The file /Users/markus/PycharmProjects/project\ with\ spaces does not exist.
[2019-04-11 16:51:51][action.script] Processing output of 'output.notification' with arg 'project with spaces
'

**Comment by bchatard** [comment]
Indeed the bash part of the workflow doesn't handle space in directory name

**Comment by bchatard** [comment]
@Knapsack44 please take a look on latest version (1.0.8)

**Comment by Knapsack44** [comment]
Still getting the same behaviour and error with 1.0.8

[Full Debug Log](https://pastebin.com/FbS027NT)

**Comment by bchatard** [comment]
Can you check if the configuration is ok in the workflow?

![issue_12](https://user-images.githubusercontent.com/829364/56017335-34935f00-5cff-11e9-9e89-8faeafd25c73.gif)

**Comment by Knapsack44** [comment]
Seems fine.
![image](https://user-images.githubusercontent.com/525624/56017574-006c6e00-5d00-11e9-8770-e3859cdd2b54.png)

**Comment by bchatard** [comment]
could you try to add `"` around `${QUERY}`

```diff
- $(${BIN} ${QUERY})
+ $(${BIN} "${QUERY}")
```

**Comment by Knapsack44** [comment]
Great, that fixed the issue.

**Comment by bchatard** [comment]
Thanks for your help! I will released the real fix now
